spring:
  application:
    name: consul-consumer
  cloud:
    consul:
      discovery:
        heartbeat:
          enabled: true
server:
  port: 8001
management:
  endpoint:
    health:
      show-details: always